UPDATE `zt_workflowdatasource` SET `name` = 'Product'                WHERE `id` = 1;
UPDATE `zt_workflowdatasource` SET `name` = 'Project'                WHERE `id` = 2;
UPDATE `zt_workflowdatasource` SET `name` = 'Product Line'           WHERE `id` = 3;
UPDATE `zt_workflowdatasource` SET `name` = 'Story'                  WHERE `id` = 4;
UPDATE `zt_workflowdatasource` SET `name` = 'Task'                   WHERE `id` = 5;
UPDATE `zt_workflowdatasource` SET `name` = 'Bug'                    WHERE `id` = 6;
UPDATE `zt_workflowdatasource` SET `name` = 'Privilege Group'        WHERE `id` = 7;
UPDATE `zt_workflowdatasource` SET `name` = 'User'                   WHERE `id` = 8;
UPDATE `zt_workflowdatasource` SET `name` = 'Product Branch'         WHERE `id` = 9;
UPDATE `zt_workflowdatasource` SET `name` = 'Release'                WHERE `id` = 10;
UPDATE `zt_workflowdatasource` SET `name` = 'Module'                 WHERE `id` = 11;
UPDATE `zt_workflowdatasource` SET `name` = 'Plan'                   WHERE `id` = 12;
UPDATE `zt_workflowdatasource` SET `name` = 'Product Type'           WHERE `id` = 13;
UPDATE `zt_workflowdatasource` SET `name` = 'Product Status'         WHERE `id` = 14;
UPDATE `zt_workflowdatasource` SET `name` = 'Product Access'         WHERE `id` = 15;
UPDATE `zt_workflowdatasource` SET `name` = 'Project Type'           WHERE `id` = 16;
UPDATE `zt_workflowdatasource` SET `name` = 'Project Status'         WHERE `id` = 17;
UPDATE `zt_workflowdatasource` SET `name` = 'Project Access'         WHERE `id` = 18;
UPDATE `zt_workflowdatasource` SET `name` = 'Release Status'         WHERE `id` = 19;
UPDATE `zt_workflowdatasource` SET `name` = 'Story Source'           WHERE `id` = 20;
UPDATE `zt_workflowdatasource` SET `name` = 'Story Priority'         WHERE `id` = 21;
UPDATE `zt_workflowdatasource` SET `name` = 'Story Status'           WHERE `id` = 22;
UPDATE `zt_workflowdatasource` SET `name` = 'Story Stage'            WHERE `id` = 23;
UPDATE `zt_workflowdatasource` SET `name` = 'Bug Severity'           WHERE `id` = 24;
UPDATE `zt_workflowdatasource` SET `name` = 'Bug Priority'           WHERE `id` = 25;
UPDATE `zt_workflowdatasource` SET `name` = 'Bug Type'               WHERE `id` = 26;
UPDATE `zt_workflowdatasource` SET `name` = 'Bug OS'                 WHERE `id` = 27;
UPDATE `zt_workflowdatasource` SET `name` = 'Bug Browser'            WHERE `id` = 28;
UPDATE `zt_workflowdatasource` SET `name` = 'Bug Status'             WHERE `id` = 29;
UPDATE `zt_workflowdatasource` SET `name` = 'Task Type'              WHERE `id` = 30;
UPDATE `zt_workflowdatasource` SET `name` = 'Task Priority'          WHERE `id` = 31;
UPDATE `zt_workflowdatasource` SET `name` = 'Task Status'            WHERE `id` = 32;
UPDATE `zt_workflowdatasource` SET `name` = 'Test Case Priority'     WHERE `id` = 33;
UPDATE `zt_workflowdatasource` SET `name` = 'Test Case Type'         WHERE `id` = 34;
UPDATE `zt_workflowdatasource` SET `name` = 'Test Case Stage'        WHERE `id` = 35;
UPDATE `zt_workflowdatasource` SET `name` = 'Test Case Status'       WHERE `id` = 36;
UPDATE `zt_workflowdatasource` SET `name` = 'Test Request Priority'  WHERE `id` = 37;
UPDATE `zt_workflowdatasource` SET `name` = 'Test Request Status'    WHERE `id` = 38;
UPDATE `zt_workflowdatasource` SET `name` = 'Feedback Status'        WHERE `id` = 39;
UPDATE `zt_workflowdatasource` SET `name` = 'Bug Resolution'         WHERE `id` = 40;
UPDATE `zt_workflowdatasource` SET `name` = 'Case'                   WHERE `id` = 41;
UPDATE `zt_workflowdatasource` SET `name` = 'Feedback Branch'        WHERE `id` = 42;
UPDATE `zt_workflowdatasource` SET `name` = 'Story Type'             WHERE `id` = 43;
UPDATE `zt_workflowdatasource` SET `name` = 'Execution'              WHERE `id` = 44;
UPDATE `zt_workflowdatasource` SET `name` = 'Project Model'          WHERE `id` = 45;
UPDATE `zt_workflowdatasource` SET `name` = 'Feedback Type'          WHERE `id` = 46;
UPDATE `zt_workflowdatasource` SET `name` = 'Feedback Suolution'     WHERE `id` = 47;
UPDATE `zt_workflowdatasource` SET `name` = 'Feedback Closed Reason' WHERE `id` = 48;
UPDATE `zt_workflowdatasource` SET `name` = 'Task Closed Reason'     WHERE `id` = 49;
UPDATE `zt_workflowdatasource` SET `name` = 'Testsuite Auth'         WHERE `id` = 50;
UPDATE `zt_workflowdatasource` SET `name` = 'Programs'               WHERE `id` = 51;
UPDATE `zt_workflowdatasource` SET `name` = 'Story Closed Reason'    WHERE `id` = 52;
UPDATE `zt_workflowdatasource` SET `name` = 'Projects'               WHERE `id` = 53;
UPDATE `zt_workflowdatasource` SET `name` = 'Tasks'                  WHERE `id` = 54;
UPDATE `zt_workflowdatasource` SET `name` = 'Groups'                 WHERE `id` = 55;
UPDATE `zt_workflowdatasource` SET `name` = 'Users'                  WHERE `id` = 56;
UPDATE `zt_workflowdatasource` SET `name` = 'Modules'                WHERE `id` = 57;
UPDATE `zt_workflowdatasource` SET `name` = 'Project Type'           WHERE `id` = 58;
UPDATE `zt_workflowdatasource` SET `name` = 'Project Status'         WHERE `id` = 59;
UPDATE `zt_workflowdatasource` SET `name` = 'Project Acl'            WHERE `id` = 60;
UPDATE `zt_workflowdatasource` SET `name` = 'Task Type'              WHERE `id` = 61;
UPDATE `zt_workflowdatasource` SET `name` = 'Task Privilege'         WHERE `id` = 62;
UPDATE `zt_workflowdatasource` SET `name` = 'Task Status'            WHERE `id` = 63;
UPDATE `zt_workflowdatasource` SET `name` = 'Feedback Status'        WHERE `id` = 64;
UPDATE `zt_workflowdatasource` SET `name` = 'Feedback Modules'       WHERE `id` = 65;
UPDATE `zt_workflowdatasource` SET `name` = 'Feedback Type'          WHERE `id` = 66;
UPDATE `zt_workflowdatasource` SET `name` = 'Feedback Suolution'     WHERE `id` = 67;
UPDATE `zt_workflowdatasource` SET `name` = 'Feedback Closed Reason' WHERE `id` = 68;
UPDATE `zt_workflowdatasource` SET `name` = 'Task Closed Reason'     WHERE `id` = 69;
