REPLACE INTO `zt_workflowaction` (`module`, `action`, `name`, `type`, `batchMode`, `extensionType`, `open`, `position`, `layout`, `show`, `order`, `buildin`, `conditions`, `verifications`, `hooks`, `linkages`, `js`, `css`, `toList`, `desc`, `createdBy`, `createdDate`, `editedBy`, `editedDate`) VALUES
('feedback',    'adminview',    '研发页面反馈详情',     'single',       'different',    'none', 'normal',       'browseandview',        'normal',       'dropdownlist', 0,      1,      '',     '',     '',     '',     '',     '',     '',     '',     'admin',        '2020-11-12 16:46:48',  '',     '0000-00-00 00:00:00'),
('feedback',    'admin',        '研发页面浏览反馈',     'single',       'different',    'none', 'normal',       'browseandview',        'normal',       'dropdownlist', 0,      1,      '',     '',     '',     '',     '',     '',     '',     '',     'admin',        '2020-11-12 16:46:48',  '',     '0000-00-00 00:00:00'),
('bug', 'batchconfirm', '批量确认',     'single',       'different',    'none', 'none', 'browseandview',        'normal',       'dropdownlist', 0,      1,      '',     '',     '',     '',     '',     '',     '',     '',     'admin',        '2020-11-12 16:46:48',  '',     '0000-00-00 00:00:00'),
('bug', 'batchresolve', '批量解决',     'single',       'different',    'none', 'none', 'browseandview',        'normal',       'dropdownlist', 0,      1,      '',     '',     '',     '',     '',     '',     '',     '',     'admin',        '2020-11-12 16:46:48',  '',     '0000-00-00 00:00:00');

REPLACE INTO `zt_workflowaction` (`module`, `action`, `name`, `type`, `batchMode`, `extensionType`, `open`, `position`, `layout`, `show`, `order`, `buildin`, `conditions`, `verifications`, `hooks`, `linkages`, `js`, `css`, `toList`, `desc`, `createdBy`, `createdDate`, `editedBy`, `editedDate`) VALUES
('testcase',    'batchcreate',  '批量创建',     'single',       'different',    'none', 'normal',       'browseandview',        'normal',       'dropdownlist', 0,      1,      '',     '',     '',     '',     '',     '',     '',     '',     '',     '2020-06-02 09:26:07',  '',     '0000-00-00 00:00:00'),
('testcase',    'batchedit',    '批量编辑',     'single',       'different',    'none', 'normal',       'browseandview',        'normal',       'dropdownlist', 0,      1,      '',     '',     '',     '',     '',     '',     '',     '',     '',     '2020-06-02 09:26:07',  '',     '0000-00-00 00:00:00'),
('testcase',    'exporttemplate',       '下载模板',     'single',       'different',    'none', 'modal',        'browseandview',        'normal',       'dropdownlist', 0,      1,      '',     '',     '',     '',     '',     '',     '',     '',     '',     '2020-06-02 09:26:07',  '',     '0000-00-00 00:00:00'),
('testcase',    'import',       '导入', 'single',       'different',    'none', 'modal',        'browseandview',        'normal',       'dropdownlist', 0,      1,      '',     '',     '',     '',     '',     '',     '',     '',     '',     '2020-06-02 09:26:07',  '',     '0000-00-00 00:00:00'),
('testcase',    'showimport',   '显示导入内容', 'single',       'different',    'none', 'normal',       'browseandview',        'normal',       'dropdownlist', 0,      1,      '',     '',     '',     '',     '',     '',     '',     '',     '',     '2020-06-02 09:26:07',  '',     '0000-00-00 00:00:00');
